Repository EveryAnalytics/react-analytics-provider, pull requests merged in 2021-08, with the labels that each got.

#5 demo app react module path 수정
  build/index.es.js
  demo/package-lock.json
  demo/package.json
  demo/src/App.js
  package-lock.json
  package.json
  src/index.tsx
Labels: bug

#7 GitHub PR 템플릿 추가
  .github/pull_request_template.md
Labels: enhancement

#6 ignore files 업데이트
  .gitignore
  .npmignore
  build/__tests__/component.spec.d.ts
  build/index.d.ts
  build/index.es.js
Labels: enhancement

#12 CI 자동화 추가
  .github/workflows/ci.yml
  src/__tests__/__snapshots__/component.spec.tsx.snap
Labels: enhancement

#22 npm 패키지에 타입 선언 추가
  package.json
Labels: bug

#41 feat: useAnalyticsPageView, AnalyticsPageView, googleAnalytics.click, analytics.click 생성
  .eslintrc.json
  demo/src/App.tsx
  demo/src/components/NavBar.tsx
  demo/src/index.tsx
  demo/src/pages/LoginPage/index.tsx
  demo/src/pages/MainPage/index.tsx
  demo/src/utils/fruitLogger/index.ts
  package-lock.json
  src/components/AnalyticsPageView/index.tsx
  src/components/AnalyticsProvider/index.tsx
  src/components/Sample.tsx
  src/components/index.ts
  src/contexts/AnalyticsProviderContext.ts
  src/contexts/index.ts
  src/hooks/index.ts
  src/hooks/useAnalyticsPageView.ts
  src/index.tsx
  src/types/common.ts
  src/utils/googleAnalytics/click.ts
  src/utils/googleAnalytics/event.ts
  src/utils/googleAnalytics/index.ts
  src/utils/googleAnalytics/initialize.ts
  src/utils/index.ts
Labels: ✨ new feature

#43 prettier, eslint 스크립트 추가
  .eslintignore
  .eslintrc.json
  .github/workflows/ci.yml
  .prettierrc
  demo/package.json
  demo/src/App.tsx
  demo/src/components/NavBar.tsx
  demo/src/index.css
  demo/src/pages/LoginPage/index.tsx
  demo/src/pages/MainPage/index.tsx
  demo/src/router/Route.ts
  demo/src/router/navigate.ts
  demo/src/utils/location.ts
  demo/tsconfig.json
  package-lock.json
  package.json
  rollup.config.js
  src/__tests__/component.spec.tsx
Labels: enhancement, 🙏 help wanted

#58 googleAnalytics.set 추가
  src/utils/googleAnalytics/index.ts
  src/utils/googleAnalytics/set.ts
Labels: ✨ new feature

#64 toast 추가
  demo/package.json
  demo/src/index.tsx
  demo/src/utils/toaster/index.tsx
  package-lock.json
Labels: 🧸 demo

#68 demo 폴더 구조 만들기 (with-cra, with-nextjs)
  .eslintignore
  demo/package-lock.json
  demo/with-cra/.gitignore
  demo/with-cra/README.md
  demo/with-cra/package-lock.json
  demo/with-cra/package.json
  demo/with-cra/public/favicon.ico
  demo/with-cra/public/index.html
  demo/with-cra/public/logo192.png
  demo/with-cra/public/logo512.png
  demo/with-cra/public/manifest.json
  demo/with-cra/public/robots.txt
  demo/with-cra/src/App.tsx
  demo/with-cra/src/components/NavBar.tsx
  demo/with-cra/src/index.css
  demo/with-cra/src/index.tsx
  demo/with-cra/src/logo.svg
  demo/with-cra/src/pages/LoginPage/index.tsx
  demo/with-cra/src/pages/MainPage/index.tsx
  demo/with-cra/src/pages/ProductsPage/index.tsx
  demo/with-cra/src/react-app-env.d.ts
  demo/with-cra/src/router/Route.ts
  demo/with-cra/src/router/navigate.ts
  demo/with-cra/src/utils/fruitLogger/index.ts
  demo/with-cra/src/utils/location.ts
  demo/with-cra/src/utils/toaster/index.tsx
  demo/with-cra/tsconfig.json
  demo/with-cra/yarn.lock
  demo/with-nextjs/.eslintrc.json
  demo/with-nextjs/.gitignore
  demo/with-nextjs/README.md
  demo/with-nextjs/next-env.d.ts
  demo/with-nextjs/next.config.js
  demo/with-nextjs/package-lock.json
  demo/with-nextjs/package.json
  demo/with-nextjs/pages/_app.tsx
  demo/with-nextjs/pages/api/hello.ts
  demo/with-nextjs/pages/index.tsx
  demo/with-nextjs/public/favicon.ico
  demo/with-nextjs/public/vercel.svg
  demo/with-nextjs/styles/Home.module.css
  demo/with-nextjs/styles/globals.css
  demo/with-nextjs/tsconfig.json
  demo/yarn.lock
  package-lock.json
Labels: 🧸 demo

#77 add CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: 📖 documentation

#83 Fix format error (eslint fix)
  demo/README.md
  demo/with-cra/src/App.tsx
  demo/with-cra/src/router/Route.tsx
Labels: 🐛 bug

#91 [fix/87] demo/with-cra GA 대시보드에 트래킹 반영 안되는 이슈
  src/utils/googleAnalytics/initialize.ts
Labels: 🐛 bug

#94 CONTRIBUTING.md 추가
  CONTRIBUTING.md
Labels: 📖 documentation

#95 README 꾸미기
  .all-contributorsrc
  README.md
Labels: 📖 documentation

#92 feat/74 jest.config.js 분리
  jest.config.js
  package-lock.json
  package.json
Labels: 🧪 test

#104 README에 all-contributors table 코드 추가
  README.md
Labels: 🐛 bug, 📖 documentation

#99 AnalyticsClick 구현
  src/components/AnalyticsClick/index.tsx
  src/components/index.ts
Labels: ✨ new feature

#150 test: 테스트 패키지 설치, 환경 변경
  jest.config.js
  package-lock.json
  package.json
Labels: 🧪 test

#149 test: googleAnalytics.initialize 테스트 추가
  jest.config.js
  tests/utils/googleAnalytics/initialize.test.ts
Labels: 🧪 test

#158 chore: stale봇 추가
  .github/stale.yml
Labels: enhancement

#154 feat: 기본 routing 및 page 완성
  demo/with-nextjs/package-lock.json
  demo/with-nextjs/package.json
  demo/with-nextjs/src/components/Header.tsx
  demo/with-nextjs/src/components/NavBar.tsx
  demo/with-nextjs/src/components/index.tsx
  demo/with-nextjs/src/layout/Layout.module.css
  demo/with-nextjs/src/layout/Layout.tsx
  demo/with-nextjs/src/layout/index.tsx
  demo/with-nextjs/src/pages/_app.tsx
  demo/with-nextjs/src/pages/index.tsx
  demo/with-nextjs/src/pages/login/index.tsx
  demo/with-nextjs/src/pages/products/index.module.css
  demo/with-nextjs/src/pages/products/index.tsx
  demo/with-nextjs/styles/Home.module.css
  demo/with-nextjs/yarn.lock
Labels: 🧸 demo

#167 test: Add googleAnalytics.click test code
  tests/utils/googleAnalytics/click.test.ts
Labels: 🧪 test

#113 feat: Refactor set function and implement setUserProperty function with demo
  .eslintrc.json
  demo/with-cra/src/App.tsx
  demo/with-cra/src/components/NavBar.tsx
  demo/with-cra/src/index.tsx
  demo/with-cra/src/pages/CurrencyPage/index.tsx
  demo/with-cra/src/pages/UserPropertyPage/index.tsx
  demo/with-cra/src/utils/fruitLogger/index.ts
  demo/with-cra/src/utils/toaster/index.tsx
  src/components/AnalyticsProvider/index.tsx
  src/contexts/AnalyticsProviderContext.ts
  src/utils/googleAnalytics/index.ts
  src/utils/googleAnalytics/set.ts
  src/utils/googleAnalytics/setUserProperty.ts
Labels: ✨ new feature

#169 refactor: Update window.dataLayer operator
  src/utils/googleAnalytics/initialize.ts
Labels: invalid

#176 test: Update googleAnalytics/click gtag mocking
  tests/utils/googleAnalytics/click.test.ts
Labels: invalid, 🧪 test

#178 refactor: add overloading to googleAnalytics.set
  src/utils/googleAnalytics/set.ts
Labels: enhancement

#166 feat: with-nextjs demo app에 각각의 Page들에 AnalyticsPageView 추가
  demo/with-nextjs/src/pages/index.tsx
  demo/with-nextjs/src/pages/login/index.tsx
  demo/with-nextjs/src/pages/products/index.tsx
Labels: 🧸 demo

#179 refactor: rename googleAnalytics -> googleAnalyticsHelper
  demo/with-cra/src/index.tsx
  src/utils/googleAnalytics/index.ts
  tests/utils/googleAnalytics/click.test.ts
  tests/utils/googleAnalytics/initialize.test.ts
Labels: enhancement
